export type CoffeeChatMemberCategory = "executive" | "director" | "member";

export type CoffeeChatMember = {
  id: string;
  name: string;
  role: string;
  category: CoffeeChatMemberCategory;
  major: string;
  /** Graduation year, or null when unknown / not shared. */
  graduationYear: number | null;
  bio: string;
  interests: string[];
  photo: string;
  /** Optional per-officer Calendly link; falls back to NEXT_PUBLIC_COFFEE_CHAT_CALENDLY_URL. */
  calendly?: string;
};

/** Static ICG member directory for the applicant coffee chat scheduler. */
export const COFFEE_CHAT_MEMBERS: CoffeeChatMember[] = [
  // ── Executives ──────────────────────────────────────────────────────────────
  {
    id: "khang-nguyen",
    name: "Khang Nguyen",
    role: "President",
    category: "executive",
    major: "Business Administration",
    graduationYear: 2028,
    bio: "President and founder of ICG. Happy to talk startups, podcasts, or a good hiking trail.",
    interests: ["Startups", "Podcasts", "Hiking"],
    photo: "/images/headshots/Khang Nguyen.png",
    calendly: "https://calendly.com/khantn11-uci/icg-recruitment-coffee-chat-khang-nguyen",
  },
  {
    id: "mohan-krishnan",
    name: "Mohan Krishnan",
    role: "Vice President",
    category: "executive",
    major: "Business Administration",
    graduationYear: 2028,
    bio: "Vice President and founding member. Down to chat consulting, League, or poker.",
    interests: ["League", "Poker", "Travel"],
    photo: "/images/headshots/Mohan Krishnan.png",
    calendly: "https://calendly.com/mohank2-uci/30min",
  },
  {
    id: "kim-vuong",
    name: "Kim Vuong",
    role: "Vice President",
    category: "executive",
    major: "Business Administration",
    graduationYear: 2028,
    bio: "Vice President and founding-class member. Ask about ICG, Pilates, or the best froyo spots.",
    interests: ["Pilates", "Hiking", "Froyo"],
    photo: "/images/headshots/Kim Vuong.png",
    calendly: "https://calendly.com/kimv5-uci/kim-icg",
  },
  {
    id: "michelle-choy",
    name: "Michelle Choy",
    role: "Vice President",
    category: "executive",
    major: "Business Administration",
    graduationYear: 2028,
    bio: "Vice President and founding-class member. Loves rock climbing, yoga, and a good grocery run.",
    interests: ["Rock Climbing", "Yoga", "Grocery Runs"],
    photo: "/images/headshots/Michelle Choy.png",
    calendly: "https://calendly.com/michellechoy1312/icg-coffee-chats-michelle",
  },
  {
    id: "aaron-johnson",
    name: "Aaron Johnson",
    role: "Vice President",
    category: "executive",
    major: "Business Administration & Computer Science",
    graduationYear: 2029,
    bio: "Vice President. Talk to him about building companies, go-karting, or scuba diving.",
    interests: ["Go-Karting", "Scuba Diving", "Pickleball", "Gym"],
    photo: "/images/headshots/Aaron Johnson.png",
    calendly: "https://calendly.com/aaronjj3-uci/coffee-chat-aaron-johnson",
  },

  // ── Directors ───────────────────────────────────────────────────────────────
  {
    id: "brian-lee",
    name: "Brian Lee",
    role: "Director of Marketing",
    category: "director",
    major: "Environmental Science & Policy",
    graduationYear: 2027,
    bio: "Director of Marketing. Chat with him about editing, photography, or cooking.",
    interests: ["Editing", "Photography", "Cooking"],
    photo: "/images/headshots/Brian Lee.png",
    calendly: "https://calendly.com/brianhanlee0307/30min",
  },
  {
    id: "sahana-chockalingam",
    name: "Sahana Chockalingam",
    role: "Director of Technology",
    category: "director",
    major: "Business Information Management",
    graduationYear: 2028,
    bio: "Director of Technology. Into model airplanes, junk journaling, and taekwondo.",
    interests: ["Model Airplanes", "Junk Journaling", "Taekwondo"],
    photo: "/images/headshots/Sahana Chockalingam.png",
    calendly: "https://calendly.com/chockals-uci/icg-recruitment-coffee-chat-sahana-chockalingam",
  },
  {
    id: "joel-leong",
    name: "Joel Leong",
    role: "Director of Finance",
    category: "director",
    major: "Business Administration",
    graduationYear: 2029,
    bio: "Director of Finance. Ask about finance, soccer, sitcoms, or where to eat.",
    interests: ["Soccer", "Sitcoms", "Food"],
    photo: "/images/headshots/Joel Leong.png",
    calendly: "https://calendly.com/joelleongsz/icg",
  },
  {
    id: "sonia-wang",
    name: "Sonia Wang",
    role: "Director of Operations",
    category: "director",
    major: "Business Administration",
    graduationYear: 2029,
    bio: "Director of Operations. Loves reading, knitting, and journaling.",
    interests: ["Reading", "Knitting", "Journaling"],
    photo: "/images/headshots/Sonia Wang.png",
    calendly: "https://calendly.com/sqwang-uci/30min",
  },
  {
    id: "trinity-nguyen",
    name: "Trinity Nguyen",
    role: "Director of Corporate Relations",
    category: "director",
    major: "Business Administration",
    graduationYear: 2029,
    bio: "Director of Corporate Relations. A Taylor Swift fan who loves reading and scrapbooking.",
    interests: ["Taylor Swift", "Reading", "Scrapbooking"],
    photo: "/images/headshots/Trinity Nguyen.png",
    calendly: "https://calendly.com/trinikn1-uci/new-meeting-trinity-nguyen",
  },
  {
    id: "krish-marwah",
    name: "Krish Marwah",
    role: "Director of Sourcing",
    category: "director",
    major: "Business Administration",
    graduationYear: 2027,
    bio: "Director of Sourcing. Talk to him about acting, film & TV, soccer, or anime.",
    interests: ["Acting", "Film & TV", "Soccer", "Anime"],
    photo: "/images/headshots/Krish Marwah.png",
    calendly: "https://calendly.com/kmarwah-uci/30min",
  },
  {
    id: "lucia-morales",
    name: "Lucia Morales",
    role: "Director of Socials",
    category: "director",
    major: "Business Administration",
    graduationYear: 2029,
    bio: "Director of Socials. Into baking cookies, writing poetry, and café hopping.",
    interests: ["Baking", "Poetry", "Café Hopping"],
    photo: "/images/headshots/Lucia Morales.png",
    calendly: "https://calendly.com/luciaam2-uci/30min?month=2026-09",
  },

  // ── Consultants ─────────────────────────────────────────────────────────────
  {
    id: "madison-lee",
    name: "Madison Lee",
    role: "Consultant",
    category: "member",
    major: "Environmental Engineering",
    graduationYear: 2029,
    bio: "Consultant. Loves drawing, sticker collecting, and hiking.",
    interests: ["Drawing", "Sticker Collecting", "Hiking"],
    photo: "/images/headshots/Madison Lee.png",
    calendly: "https://cal.com/madison-vesper-lee-0qh5tw/30min",
  },
  {
    id: "vasavi-suresh",
    name: "Vasavi Suresh",
    role: "Consultant",
    category: "member",
    major: "Business Administration",
    graduationYear: 2029,
    bio: "Consultant. Chat with her about cooking, tidepooling, or hiking.",
    interests: ["Cooking", "Tidepooling", "Hiking"],
    photo: "/images/headshots/Vasavi Suresh.png",
    calendly: "https://calendly.com/vasavis-uci/new-meeting",
  },
  {
    id: "megan-sinaga",
    name: "Megan Sinaga",
    role: "Consultant",
    category: "member",
    major: "Business Economics",
    graduationYear: 2029,
    bio: "Consultant. Into running, exploring new places, and making her own clothes.",
    interests: ["Running", "Exploring", "Sewing"],
    photo: "/images/headshots/Megan Sinaga.png",
    calendly: "https://calendly.com/msinaga-uci/30min?back=1",
  },
  {
    id: "ethan-huang",
    name: "Ethan Huang",
    role: "Consultant",
    category: "member",
    major: "Business Economics",
    graduationYear: 2028,
    bio: "Consultant. Ask about aquariums, collecting, or lacrosse.",
    interests: ["Aquariums", "Collecting", "Lacrosse"],
    photo: "/images/headshots/Ethan Huang.png",
    calendly: "https://calendly.com/ethah12-uci/30min",
  },
  {
    id: "eric-zheng",
    name: "Eric Zheng",
    role: "Consultant",
    category: "member",
    major: "Data Science",
    graduationYear: 2028,
    bio: "Consultant. Loves cooking, badminton, and videography.",
    interests: ["Cooking", "Badminton", "Videography"],
    photo: "/images/headshots/Eric Zheng.png",
    calendly: "https://calendly.com/zhengeh-uci/30min",
  },
  {
    id: "sathvik-lagadapati",
    name: "Sathvik Lagadapati",
    role: "Consultant",
    category: "member",
    major: "Applied Mathematics",
    graduationYear: 2029,
    bio: "Consultant. Into art, reading, and matcha.",
    interests: ["Art", "Reading", "Matcha"],
    photo: "/images/headshots/Sathvik Lagadapati.png",
    calendly: "https://calendly.com/sathviklagadapati/30min",
  },
  {
    id: "akash-kalita",
    name: "Akash Kalita",
    role: "Consultant",
    category: "member",
    major: "Computer Science",
    graduationYear: 2029,
    bio: "Consultant. Talk to him about coding, poker, or Drake.",
    interests: ["Coding", "Poker", "Drake"],
    photo: "/images/headshots/Akash Kalita.png",
    calendly: "https://calendly.com/kalitaa1-uci/new-meeting",
  },
  {
    id: "justin-park",
    name: "Justin Park",
    role: "Committee Member",
    category: "member",
    major: "Business Economics",
    graduationYear: 2028,
    bio: "Founding-class committee member (Ops). Into the gym, music, and exploring new spots.",
    interests: ["Gym", "Music", "Exploring"],
    photo: "/images/headshots/Justin Park.png",
    calendly: "https://calendly.com/justip14-uci/30min?back=1&month=2026-09",
  },
  {
    id: "rohan-bharti",
    name: "Rohan Bharti",
    role: "Committee Member",
    category: "member",
    major: "Computer Science",
    graduationYear: 2028,
    bio: "Committee member (Social). Loves photography, music, and time with family.",
    interests: ["Photography", "Music", "Family"],
    photo: "/images/headshots/Rohan Bharti.png",
    calendly: "https://calendly.com/rbharti-uci/30min",
  },
];
