export type CoffeeChatMemberCategory = "executive" | "director" | "member";

export type CoffeeChatMember = {
  id: string;
  name: string;
  role: string;
  category: CoffeeChatMemberCategory;
  bio: string;
  interests: string[];
  photo: string;
  /** Optional per-officer Calendly link; falls back to NEXT_PUBLIC_COFFEE_CHAT_CALENDLY_URL. */
  calendly?: string;
};

/** Static ICG officer directory for the applicant coffee chat scheduler. */
export const COFFEE_CHAT_MEMBERS: CoffeeChatMember[] = [
  {
    id: "khang-nguyen",
    name: "Khang Nguyen",
    role: "President",
    category: "executive",
    bio: "Hello! I'm Khang, a 3rd-year Business Administration major specializing in finance. I love working on strategy and helping the club grow.",
    interests: ["Finance", "Strategy", "Tennis"],
    photo: "/images/headshots/Khang Nguyen.png",
  },
  {
    id: "mohan-krishnan",
    name: "Mohan Krishnan",
    role: "Vice President",
    category: "executive",
    bio: "Hi! I'm Mohan, a 3rd-year Computer Science and Economics double major. I'm passionate about tech consulting and building impactful products.",
    interests: ["Tech Consulting", "Coding", "Basketball"],
    photo: "/images/headshots/Mohan Krishnan.png",
  },
  {
    id: "michelle-choy",
    name: "Michelle Choy",
    role: "Vice President",
    category: "executive",
    bio: "Hey! I'm Michelle, a 3rd-year Business Administration major. I enjoy leading project teams and developing client relationships.",
    interests: ["Leadership", "Hiking", "Cooking"],
    photo: "/images/headshots/Michelle Choy.png",
  },
  {
    id: "kim-vuong",
    name: "Kim Vuong",
    role: "Vice President",
    category: "executive",
    bio: "Hi there! I'm Kim, a 3rd-year Economics major with a focus on data analytics. I'm excited to connect and share my consulting journey.",
    interests: ["Data Analytics", "Photography", "Reading"],
    photo: "/images/headshots/Kim Vuong.png",
  },
  {
    id: "aaron-johnson",
    name: "Aaron Johnson",
    role: "Vice President",
    category: "executive",
    bio: "Hey! I'm Aaron, passionate about management consulting and driving organizational change. Let's chat about careers and ICG!",
    interests: ["Consulting", "Soccer", "Chess"],
    photo: "/images/headshots/Aaron Johnson.png",
  },
  {
    id: "brian-lee",
    name: "Brian Lee",
    role: "Director of Marketing",
    category: "director",
    bio: "Hi! I'm Brian, a 2nd-year Business major. I lead our marketing efforts and love crafting stories that connect with people.",
    interests: ["Marketing", "Design", "Music"],
    photo: "/images/headshots/Brian Lee.png",
  },
  {
    id: "justin-park",
    name: "Justin Park",
    role: "Director of Operations",
    category: "director",
    bio: "Hello! I'm Justin, a 3rd-year Information & Computer Science major. I keep our club running smoothly and love optimizing processes.",
    interests: ["Operations", "Gaming", "Weightlifting"],
    photo: "/images/headshots/Justin Park.png",
  },
  {
    id: "sahana-chockalingam",
    name: "Sahana Chockalingam",
    role: "Director of Technology",
    category: "director",
    bio: "Hi! I'm Sahana, a 3rd-year CS major. I oversee our tech projects and am always excited to talk about product and engineering consulting.",
    interests: ["Technology", "Yoga", "Traveling"],
    photo: "/images/headshots/Sahana Chockalingam.png",
  },
  {
    id: "joel-leong",
    name: "Joel Leong",
    role: "Director of Finance",
    category: "director",
    bio: "Hey! I'm Joel, a 2nd-year Business Economics major. I'm passionate about financial modeling and investment strategy.",
    interests: ["Finance", "Golf", "Piano"],
    photo: "/images/headshots/Joel Leong.png",
  },
  {
    id: "trinity-nguyen",
    name: "Trinity Nguyen",
    role: "Director of Recruitment",
    category: "director",
    bio: "Hi! I'm Trinity, a 3rd-year Psychology and Business double major. I love connecting with new people and building our club community.",
    interests: ["Recruitment", "Art", "Volleyball"],
    photo: "/images/headshots/Trinity Nguyen.png",
  },
  {
    id: "krish-marwah",
    name: "Krish Marwah",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Krish, a 2nd-year CS & Management Science major. I'm eager to chat about tech consulting and career development.",
    interests: ["Consulting", "Cricket", "Hackathons"],
    photo: "/images/headshots/Krish Marwah.png",
  },
  {
    id: "lucia-morales",
    name: "Lucia Morales",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Lucia, a 2nd-year Business Administration major. I love working on real-world case studies and developing my consulting skills.",
    interests: ["Strategy", "Running", "Baking"],
    photo: "/images/headshots/Lucia Morales.png",
  },
  {
    id: "abby-luong",
    name: "Abby Luong",
    role: "Associate Consultant",
    category: "member",
    bio: "Hello! I'm Abby, a 2nd-year Economics major. Excited to share my ICG experience and chat about the consulting industry.",
    interests: ["Economics", "Reading", "Badminton"],
    photo: "/images/headshots/Abby Luong.png",
  },
  {
    id: "akash-kalita",
    name: "Akash Kalita",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Akash, a 2nd-year Data Science major. Passionate about data-driven consulting and turning insights into strategy.",
    interests: ["Data Science", "Basketball", "Cooking"],
    photo: "/images/headshots/Akash Kalita.png",
  },
  {
    id: "eric-zheng",
    name: "Eric Zheng",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Eric, a 2nd-year Business Administration major. I enjoy case competitions and developing client-facing skills.",
    interests: ["Finance", "Soccer", "Chess"],
    photo: "/images/headshots/Eric Zheng.png",
  },
  {
    id: "ethan-huang",
    name: "Ethan Huang",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Ethan, a 2nd-year CS major. I love bridging tech and business and would love to chat about my ICG journey.",
    interests: ["Technology", "Piano", "Hiking"],
    photo: "/images/headshots/Ethan Huang.png",
  },
  {
    id: "ian-su",
    name: "Ian Su",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Ian, a 2nd-year Business Economics major. Ask me anything about the recruitment process or life at ICG!",
    interests: ["Strategy", "Tennis", "Film"],
    photo: "/images/headshots/Ian Su.png",
  },
  {
    id: "madison-lee",
    name: "Madison Lee",
    role: "Associate Consultant",
    category: "member",
    bio: "Hello! I'm Madison, a 2nd-year Management Science major. I'm passionate about organizational consulting and team dynamics.",
    interests: ["Leadership", "Dance", "Traveling"],
    photo: "/images/headshots/Madison Lee.png",
  },
  {
    id: "megan-sinaga",
    name: "Megan Sinaga",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Megan, a 2nd-year Business Administration major. I love client projects and can't wait to share my consulting experience!",
    interests: ["Marketing", "Painting", "Yoga"],
    photo: "/images/headshots/Megan Sinaga.png",
  },
  {
    id: "parav-salaniwal",
    name: "Parav Salaniwal",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Parav, a 2nd-year CS and Business Information Management major. I enjoy working on tech strategy engagements.",
    interests: ["Tech Strategy", "Cricket", "Cooking"],
    photo: "/images/headshots/Parav Salaniwal.png",
  },
  {
    id: "rohan-bharti",
    name: "Rohan Bharti",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Rohan, a 2nd-year Economics and Data Science major. Always happy to chat about consulting and career development!",
    interests: ["Data", "Football", "Guitar"],
    photo: "/images/headshots/Rohan Bharti.png",
  },
  {
    id: "sathvik-lagadapati",
    name: "Sathvik Lagadapati",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Sathvik, a 2nd-year Computer Science major. Excited to talk about how tech and consulting intersect.",
    interests: ["Technology", "Badminton", "Reading"],
    photo: "/images/headshots/Sathvik Lagadapati.png",
  },
  {
    id: "sonia-wang",
    name: "Sonia Wang",
    role: "Associate Consultant",
    category: "member",
    bio: "Hello! I'm Sonia, a 2nd-year Business Administration major. I love collaborative projects and would love to connect with you!",
    interests: ["Strategy", "Cooking", "Pilates"],
    photo: "/images/headshots/Sonia Wang.png",
  },
  {
    id: "vasavi-suresh",
    name: "Vasavi Suresh",
    role: "Associate Consultant",
    category: "member",
    bio: "Hi! I'm Vasavi, a 2nd-year Economics major. Passionate about sustainability consulting and social impact.",
    interests: ["Sustainability", "Volleyball", "Art"],
    photo: "/images/headshots/Vasavi Suresh.png",
  },
  {
    id: "zach-bosa",
    name: "Zach Bosa",
    role: "Associate Consultant",
    category: "member",
    bio: "Hey! I'm Zach, a 2nd-year Business Administration major. I enjoy diving into market research and competitive analysis.",
    interests: ["Research", "Basketball", "Podcasts"],
    photo: "/images/headshots/Zach Bosa.png",
  },
];
